### ISSUE TITLE
Any plans to finish the React demo?

### ISSUE THREAD

**Issue by John30013** [wi3land/ionic-appauth-react-demo#1]
Hi, Matthew--

I'm trying to create an Ionic React app using your package for OAuth, but the react demo doesn't work. In fact, it doesn't even compile (seemingly because of a dependency error related to the typescript-eslint package). So I copied your code into my own app, which allowed it to compile, and I set it to use my company's internal OAuth provider. But the app sits at the "Awaiting Auth" display and  I can't figure out how to get past that. 

I am somewhat fluent in Angular and Vue as well, (and now I'm starting to wish I'd used one of those frameworks to create my mobile app), but our development team uses React for other related projects, so I decided to write the mobile app in Ionic-React. I've considered trying to get your Angular+Capacitor demo working with my company's OAuth provider and then trying to complete the React demo by analogy with the Angular demo. But that would probably take me a week or two, and from what I can tell by comparing the Angular and React demo code, I believe the React demo is nearly complete, but I'm not sure I know how to figure out what's missing and how to fill that in.

So, do you have any plans to finish the React demo any time soon? If not, could you give me some guidance about what needs to be done to finish it? I'm trying to get the beta version of our mobile app out the door in time for some conferences in May, so I have about two months to solve this. Obviously my schedule is not your problem, but I would appreciate any guidance/pointers you can provide toward getting the demo to work.

**Comment by wi3land** [comment]
Please Refer to https://github.com/wi3land/ionic-appauth/issues/8.

I created this and attempted to build a react example. However, like you I am primarily a Angular Developer. I left this demo up in the hopes a react developer would come along and maybe help me finish it or at least point me in the right direction.

I am currently working on a large amount of projects for my work, so I don't have the personal time to do anything on this at the moment.

**Comment by John30013** [comment]
Thanks for your reply. I completely understand where you're coming from.

**Comment by wi3land** [comment]
Just a quick not, I spent the past few days building the react demo. i think i have it doing everything that the ng and capacitor demos do.

**Comment by John30013** [comment]
Oh, that's, awesome. Thanks. I'll take a look.
